### ISSUE TITLE
I added the scene to a project and nothing happens...

### ISSUE THREAD

**Issue by thewhiterabbit** [aiczk/Unity-Procedural-terrain-generation#1]
In Unity 2020.1.6f1 I created a new project, drag this asset into the project, then added the scene from this asset and clicked play. Nothing happened. it's just a blank camera view.

What steps are needed to get this to function as a terrain generator?

**Comment by aiczk** [comment]
Thank you for using my assets.
I have made them compatible with 2020.1.6f1 and have committed a bug fix so you can use that one.
Thanks for the report.
